# The FlockIt app icon: option 45, the leaning F rooster.
# One description of the mark -> the adaptive icon vectors (foreground, monochrome, background),
# the legacy webp mipmaps and a preview.  Run:  python design/make_app_icon.py
#
# The mark is six separate parts in a 200-unit drawing space (the same numbers as FlockLoader.kt):
#   stem  (the rooster), top arm, middle arm, comb, beak, eye — leaning forward by 12 degrees.
import math, os
from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "app", "src", "main", "res")

WHITE = "#F2F2F0"; RED = "#E5534B"; BEAK = "#F0A23A"; BLACK = "#000000"
LEAN = math.tan(math.radians(12))
K = 0.5523


def rrect(x, y, w, h, r):
    k = K * r
    return [("M", (x + r, y)), ("L", (x + w - r, y)), ("C", (x + w - r + k, y), (x + w, y + r - k), (x + w, y + r)),
            ("L", (x + w, y + h - r)), ("C", (x + w, y + h - r + k), (x + w - r + k, y + h), (x + w - r, y + h)),
            ("L", (x + r, y + h)), ("C", (x + r - k, y + h), (x, y + h - r + k), (x, y + h - r)),
            ("L", (x, y + r)), ("C", (x, y + r - k), (x + r - k, y), (x + r, y)), ("Z",)]


def circle(cx, cy, r):
    k = K * r
    return [("M", (cx + r, cy)), ("C", (cx + r, cy + k), (cx + k, cy + r), (cx, cy + r)), ("C", (cx - k, cy + r), (cx - r, cy + k), (cx - r, cy)),
            ("C", (cx - r, cy - k), (cx - k, cy - r), (cx, cy - r)), ("C", (cx + k, cy - r), (cx + r, cy - k), (cx + r, cy)), ("Z",)]


def poly(*pts):
    return [("M", pts[0])] + [("L", p) for p in pts[1:]] + [("Z",)]


S = 0.82   # comb size
PARTS = [   # name, colour, path (drawing order)
    ("comb", RED, circle(73 - 12 * S, 50 + 5 * S, 7.5 * S) + circle(73, 50, 9 * S) + circle(73 + 12 * S, 50 + 5 * S, 7.5 * S)),
    ("stem", WHITE, rrect(60, 56, 26, 104, 8)),
    ("top arm", WHITE, rrect(94, 60, 60, 24, 8)),
    ("middle arm", WHITE, rrect(94, 100, 42, 24, 8)),
    ("beak", BEAK, poly((60, 70), (42, 77), (60, 85))),
    ("eye", BLACK, circle(72, 74, 3.8)),
]
SHIFT = -4.0   # the lean pushes the mark right of centre; bring it back


def place(p, scale, off):
    """Drawing units -> leaning -> the target canvas."""
    x, y = p
    xl = x + 2 + SHIFT - LEAN * (y - 100)
    return off + xl * scale, off + y * scale


def path_data(path, scale, off):
    out = []
    for seg in path:
        if seg[0] == "Z":
            out.append("Z")
        else:
            out.append(seg[0] + " " + " ".join("%.2f,%.2f" % place(p, scale, off) for p in seg[1:]))
    return " ".join(out)


def flatten(path, scale, off, steps=14):
    """Bezier path -> list of polygons (for the bitmap renders)."""
    polys, cur, pen = [], [], None
    for seg in path:
        if seg[0] == "M":
            if cur: polys.append(cur)
            pen = place(seg[1], scale, off); cur = [pen]
        elif seg[0] == "L":
            pen = place(seg[1], scale, off); cur.append(pen)
        elif seg[0] == "C":
            p0 = pen; p1, p2, p3 = (place(q, scale, off) for q in seg[1:])
            for i in range(1, steps + 1):
                t = i / steps; a = (1 - t) ** 3; b = 3 * (1 - t) ** 2 * t; c = 3 * (1 - t) * t * t; d = t ** 3
                cur.append((a * p0[0] + b * p1[0] + c * p2[0] + d * p3[0], a * p0[1] + b * p1[1] + c * p2[1] + d * p3[1]))
            pen = p3
        elif seg[0] == "Z":
            polys.append(cur); cur = []
    if cur: polys.append(cur)
    return polys


# ------------------------------------------------------------------ adaptive icon (108 dp canvas; the 200-unit
# drawing fills the 72 dp a launcher shows, so the mark sits inside the 66 dp safe zone)
A_SCALE, A_OFF = 72 / 200, 18.0
HEAD = ('<?xml version="1.0" encoding="utf-8"?>\n<!-- FlockIt mark: the leaning F rooster. Generated by design/make_app_icon.py - edit there. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">\n')

fg = HEAD + "".join(f'    <!-- {name} -->\n    <path android:fillColor="{col}" android:pathData="{path_data(p, A_SCALE, A_OFF)}" />\n' for name, col, p in PARTS) + "</vector>\n"
open(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), "w", encoding="utf-8").write(fg)

# themed (monochrome) icon: one colour, the eye is a hole in the stem
mono = HEAD
for name, col, p in PARTS:
    if name == "eye": continue
    d = path_data(p, A_SCALE, A_OFF)
    if name == "stem":
        d += " " + path_data(PARTS[-1][2], A_SCALE, A_OFF)
        mono += f'    <path android:fillColor="#FFFFFF" android:fillType="evenOdd" android:pathData="{d}" />\n'
    else:
        mono += f'    <path android:fillColor="#FFFFFF" android:pathData="{d}" />\n'
mono += "</vector>\n"
open(os.path.join(RES, "drawable", "ic_launcher_monochrome.xml"), "w", encoding="utf-8").write(mono)

open(os.path.join(RES, "drawable", "ic_launcher_background.xml"), "w", encoding="utf-8").write(
    '<?xml version="1.0" encoding="utf-8"?>\n<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
    '    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">\n'
    '    <path android:fillColor="#000000" android:pathData="M0,0h108v108h-108z" />\n</vector>\n')

ADAPTIVE = ('<?xml version="1.0" encoding="utf-8"?>\n<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
            '    <background android:drawable="@drawable/ic_launcher_background" />\n'
            '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
            '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n</adaptive-icon>\n')
for n in ("ic_launcher.xml", "ic_launcher_round.xml"):
    open(os.path.join(RES, "mipmap-anydpi-v26", n), "w", encoding="utf-8").write(ADAPTIVE)


# ------------------------------------------------------------------ legacy bitmaps (phones before Android 8)
def render(px, round_=False):
    ss = 4; n = px * ss
    im = Image.new("RGBA", (n, n), (0, 0, 0, 0)); dr = ImageDraw.Draw(im)
    if round_: dr.ellipse([0, 0, n - 1, n - 1], fill=BLACK)
    else: dr.rounded_rectangle([0, 0, n - 1, n - 1], radius=n * 0.22, fill=BLACK)
    for _, col, p in PARTS:
        for pg in flatten(p, n / 200, 0.0):
            dr.polygon(pg, fill=col)
    return im.resize((px, px), Image.LANCZOS)


for dens, px in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
    d = os.path.join(RES, f"mipmap-{dens}")
    render(px).save(os.path.join(d, "ic_launcher.webp"), "WEBP", quality=95)
    render(px, True).save(os.path.join(d, "ic_launcher_round.webp"), "WEBP", quality=95)

prev = Image.new("RGB", (640, 300), (38, 39, 43))
for i, im in enumerate((render(256), render(256, True))):
    prev.paste(im, (22 + i * 278, 22), im)
small = render(48, True); prev.paste(small, (580, 126), small)
prev.save(os.path.join(HERE, "app-icon-preview.png"))

# the logo for the repository page (README): the icon as a 512 px picture and as a vector
render(512).save(os.path.join(HERE, "logo.png"))
def svg_path(path):
    return " ".join("Z" if seg[0] == "Z" else seg[0] + " " + " ".join("%.2f,%.2f" % place(q, 1.0, 0.0) for q in seg[1:]) for seg in path)
open(os.path.join(HERE, "logo.svg"), "w", encoding="utf-8").write(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200" width="512" height="512">\n'
    '  <rect width="200" height="200" rx="44" fill="#000000"/>\n' +
    "".join('  <path fill="%s" d="%s"/>\n' % (col, svg_path(pth)) for _, col, pth in PARTS) + '</svg>\n')

# ------------------------------------------------------------------ a preview of the loading animation (same steps as
# FlockLoader.kt): each part is moved into place whole — stem, top arm, middle arm, comb, beak, eye — held, cleared.
STEPS = {"stem": (0.00, 0.17, 0, 30), "top arm": (0.14, 0.31, 34, 0), "middle arm": (0.27, 0.44, 30, 0),
         "comb": (0.41, 0.56, 0, -24), "beak": (0.53, 0.66, -24, 0), "eye": (0.64, 0.74, 0, 0)}
FADE_FROM = 0.90


def shifted(path, dx, dy):
    return [seg if seg[0] == "Z" else (seg[0],) + tuple((x + dx, y + dy) for x, y in seg[1:]) for seg in path]


def loader_frame(p, px=220):
    ss = 3; n = px * ss
    im = Image.new("RGBA", (n, n), (0, 0, 0, 255))
    fade = 1 - (p - FADE_FROM) / (1 - FADE_FROM) if p > FADE_FROM else 1.0
    for name, col, path in PARTS:
        t0, t1, dx, dy = STEPS[name]
        t = min(1.0, max(0.0, (p - t0) / (t1 - t0)))
        if t <= 0: continue
        e = 1 - (1 - t) ** 3
        alpha = int(255 * min(1.0, t * 2.5) * fade)
        layer = Image.new("RGBA", (n, n), (0, 0, 0, 0)); dr = ImageDraw.Draw(layer)
        rgb = tuple(int(col[i:i + 2], 16) for i in (1, 3, 5))
        for pg in flatten(shifted(path, dx * (1 - e), dy * (1 - e)), n / 200, 0.0):
            dr.polygon(pg, fill=rgb + (alpha,))
        im = Image.alpha_composite(im, layer)
    return im.resize((px, px), Image.LANCZOS).convert("P", palette=Image.ADAPTIVE, colors=64)


frames = [loader_frame(i / 56) for i in range(57)]
frames[0].save(os.path.join(HERE, "loader-preview.gif"), save_all=True, append_images=frames[1:], duration=33, loop=0, disposal=2)
print("icon written")
